$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: main
endpoint_name: car-classifier
model: azureml:car-classifier:3
code_configuration:
  code: 
    local_path: ./src
  scoring_script: score.py
environment: azureml:aml-inference:7
instance_type: Standard_F2s_v2
instance_count: 1